### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by Mesteery** [readthedocs-fr/bindea#1]
Pourquoi ne pas faire un monorepo avec https://github.com/readthedocs-fr/bin-vscode ?
On renomme le repo en `bin-extensions` (par exemple) avec une arborescence comme :
```
vscode/
  ...
jetbrains/
  ...
README.md
```

**Comment by Hokkaydo** [comment]
Mmh why not, on peut setup ça si tu veux. 
Peut-être juste attendre que les 2 extensions soient sur une versions stable et ensuite on fusionnera les dépôts.

**Comment by Mesteery** [comment]
Oui.
Sinon, ça devrait être plus compliqué niveau CI.

**Comment by Hokkaydo** [comment]
Franchement, ça peut aller. Faudra juste spécifier le dir à watch.
Après j'hésite quand même parce que ça reste 2 projets différents avec 2 langages différents pour 2 plateformes différentes. 
Un dépôt regroupe les sources d'un seul projet normalement

**Comment by Mesteery** [comment]
Là c'est deux projets pour un plugin en rapport avec `bin` pour un IDE, c'est très proche, même si c'est pas le même langage

**Comment by Hokkaydo** [comment]
Mmh, pas convaincu.
@AntoineJT t'en penses quoi ?

**Comment by AntoineJT** [comment]
Perso, j'aime pas l'idée de regrouper les deux repos
